---
- name: 3D Printer Pi Setup
  hosts: all
  become: true
  vars:
    ssh_pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF5Buzvlm9muLrosWs1MfpnecnxzIlSoox1OF8LkRAmD tig@tiga.tech
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: PrinterPi
        use: debian
      notify: Reboot

    - name: Install SSH key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ ssh_pubkey }}"

    - name: Copy klipper_config directory contents
      ansible.builtin.copy:
        src: "{{ item.root + item.path }}"
        dest: /home/{{ ansible_user }}/klipper_config/{{ item.path }}
        mode: 0644
        directory_mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop: >-
        {{ lookup('filetree', '../klipper_config/', wantlist=True) }}
      loop_control:
        label: "{{ item.path }}"
      when: item.state == 'file'
      notify: Restart printer services

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

    - name: Restart printer services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - crowsnest
        - klipper
        - moonraker
        - sonar
